# This file was generated by GoReleaser. DO NOT EDIT.
cask "coucou" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "5ac87ed9874b2c23432014611fea92eca3943fe7042503e9d8a8e8ee34b49010"
      url "https://github.com/joelhelbling/coucou/releases/download/v#{version}/coucou_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "6826643ce9d93ec78c8a9898c87f4f0a67438d517ace377dcdc5e2b566ef3f04"
      url "https://github.com/joelhelbling/coucou/releases/download/v#{version}/coucou_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "aef0ee08e494065ff9ed67c3d56c6e74e374b8b9bc70690773b5bdb1728337ed"
      url "https://github.com/joelhelbling/coucou/releases/download/v#{version}/coucou_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "f86e22d9f7e0314945f5805b5914dfe3c26b651a5abf902d7f4cc4715b87318c"
      url "https://github.com/joelhelbling/coucou/releases/download/v#{version}/coucou_#{version}_linux_arm64.tar.gz"
    end
  end

  name "coucou"
  desc "A project-scoped TUI task scheduler for shell commands"
  homepage "https://github.com/joelhelbling/coucou"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "coucou"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/coucou"]
    end
  end

  # No zap stanza required

end
