# This file was generated by GoReleaser. DO NOT EDIT.
cask "coucou" do
  version "0.2.0"

  on_macos do
    on_arm do
      sha256 "f73cfd0c3d7039d7f5ff358630bd836628da1d1bd0488c082851b475670d3463"
      url "https://github.com/joelhelbling/coucou/releases/download/v#{version}/coucou_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "023408d45c7fefd9d7b09575385c4689ee8cdc527d973dea5b79655bd613e2c6"
      url "https://github.com/joelhelbling/coucou/releases/download/v#{version}/coucou_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "5e4664f70cde4605fda55472f4516cef3f670674a93d07fc72e60eb37fe2805f"
      url "https://github.com/joelhelbling/coucou/releases/download/v#{version}/coucou_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "6146183f0e78947f608b76e6903f9939bbb2a467a663a12dafa79bb1eb5591a5"
      url "https://github.com/joelhelbling/coucou/releases/download/v#{version}/coucou_#{version}_linux_amd64.tar.gz"
    end
  end

  name "coucou"
  desc "A project-scoped TUI task scheduler for shell commands"
  homepage "https://github.com/joelhelbling/coucou"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "coucou"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/coucou"]
    end
  end

  # No zap stanza required
end
