# This file was generated by GoReleaser. DO NOT EDIT.
cask "coucou" do
  version "0.1.1"

  on_macos do
    on_arm do
      sha256 "14ca2c062b32567bcafd8d616ae2dc02143d31cbf742fa7620b628a57a6994aa"
      url "https://github.com/joelhelbling/coucou/releases/download/v#{version}/coucou_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "38f498e1c96177d4c4838359b6a2727e540b77618f54c28dd6838ebb6f4a599a"
      url "https://github.com/joelhelbling/coucou/releases/download/v#{version}/coucou_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "a240be65b203ee7950c3898ff3c7d1ff1656d4ebceb3502773b707f236181f1e"
      url "https://github.com/joelhelbling/coucou/releases/download/v#{version}/coucou_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "862c21adb05147ffcf982a2c5f6f322b1e476170ee1fd32c69c0e246a00ab924"
      url "https://github.com/joelhelbling/coucou/releases/download/v#{version}/coucou_#{version}_linux_amd64.tar.gz"
    end
  end

  name "coucou"
  desc "A project-scoped TUI task scheduler for shell commands"
  homepage "https://github.com/joelhelbling/coucou"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "coucou"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/coucou"]
    end
  end

  # No zap stanza required
end
