# This file was generated by GoReleaser. DO NOT EDIT.
cask "kkullm" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "ea0162d47f9bcffc017795a754cb85ae4f51bfe91eb7608dfb5538e869f30241"
      url "https://github.com/joelhelbling/kkullm/releases/download/v#{version}/kkullm_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "7564fcf139f1dc19805d64c6f96bbfeb6aecc089989ff8585ad5afc19b8dffe2"
      url "https://github.com/joelhelbling/kkullm/releases/download/v#{version}/kkullm_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "b20777da58d60a01b6b10e82cf8a619d02e73981022407799e2f3fd4f5c2cbb0"
      url "https://github.com/joelhelbling/kkullm/releases/download/v#{version}/kkullm_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "7e329e42bece2320edcb5d133805e168d262e42292b08016dd4c773ab3013a1c"
      url "https://github.com/joelhelbling/kkullm/releases/download/v#{version}/kkullm_#{version}_linux_arm64.tar.gz"
    end
  end

  name "kkullm"
  desc "Agent orchestration system based on the blackboard pattern"
  homepage "https://github.com/joelhelbling/kkullm"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kkullm"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kkullm"]
    end
  end

  # No zap stanza required

end
