# This file was generated by GoReleaser. DO NOT EDIT.
cask "tabb" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "1d7ed3b278f458adb6f32382c58ad9696f78466f6134e8c10bd48f5baba66e81"
      url "https://github.com/joelhelbling/tabb/releases/download/v#{version}/tabb_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "3cef7f0adbb25bb1a550b6e66d8d68a582df882056843d3dddc796ed6e768ee4"
      url "https://github.com/joelhelbling/tabb/releases/download/v#{version}/tabb_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "56b8a57aa2ad704e704648ab3fbe7d05b569331e66ea495f799f3d909b330b0d"
      url "https://github.com/joelhelbling/tabb/releases/download/v#{version}/tabb_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "aff9c57861c7a06e1784e81d82e037fb28903c24d54c94ff9206ba6cf02ab177"
      url "https://github.com/joelhelbling/tabb/releases/download/v#{version}/tabb_#{version}_linux_arm64.tar.gz"
    end
  end

  name "tabb"
  desc "Manage Chrome browser tabs from the terminal or an AI assistant"
  homepage "https://github.com/joelhelbling/tabb"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tabb"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tabb"]
    end
  end

  # No zap stanza required

end
