# This file was generated by GoReleaser. DO NOT EDIT.
cask "tabb" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "bfc0f448392e34dcf4dd2d5f4cd0e3cdc968d18ab1bf5a421ee40c32ef69f8c7"
      url "https://github.com/joelhelbling/tabb/releases/download/v#{version}/tabb_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "3f78ba6271dd4d054ed5e2567cede2c5ac816ab7f2fb6007ccc4e63c0ec4392b"
      url "https://github.com/joelhelbling/tabb/releases/download/v#{version}/tabb_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "d6f72ba110ee1a435feae86e2088c1ad2f23e4b8fb8e894733d92129e4755fbe"
      url "https://github.com/joelhelbling/tabb/releases/download/v#{version}/tabb_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "af0f3d1682c678b1c774e5a6ae79de367107b502b0e2bc19be4bf6b4c35684d4"
      url "https://github.com/joelhelbling/tabb/releases/download/v#{version}/tabb_#{version}_linux_arm64.tar.gz"
    end
  end

  name "tabb"
  desc "Manage Chrome browser tabs from the terminal or an AI assistant"
  homepage "https://github.com/joelhelbling/tabb"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tabb"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tabb"]
    end
  end

  # No zap stanza required

end
